#!/usr/bin/env python3
"""Assemble the §3 + §6.3 reading copy the advisor asked for.

The theory and the attack have to say the same thing in the same words, so this pulls both from
their source drafts rather than letting a copy drift. It also checks that the four outcome labels
of Corollary 1b are exactly the labels Table 2 and §6.3 use.

    python paper/make_read_s3_s63.py   ->  paper/generated/read_s3_s63.md
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "generated" / "read_s3_s63.md"

SOURCES = {
    "s3": (ROOT / "draft_s3_s5.md", "## 3 Setup and Test", "## 4.x"),
    "cor": (ROOT / "draft_analysis.md", "## Corollary 1 (", "## Placement and scope notes"),
    "s63": (ROOT / "draft_s5_s6.md", "### 6.3 An adaptive distiller", "### 6.4 Scope"),
}

# The words that must be identical on both sides.
OUTCOME_WORDS = ["evade", "frame", "joint claim", "laundering"]


def slice_between(path: Path, start: str, end: str) -> str:
    text = path.read_text()
    i = text.find(start)
    if i < 0:
        sys.exit(f"{path.name}: heading not found: {start!r}")
    j = text.find(end, i + len(start))
    return text[i : j if j > 0 else len(text)].rstrip() + "\n"


def main() -> None:
    parts = {k: slice_between(*v) for k, v in SOURCES.items()}

    # Consistency check: every outcome word used by the corollary must appear in §6.3, and vice versa.
    cor, s63 = parts["cor"].lower(), parts["s63"].lower()
    missing = [w for w in OUTCOME_WORDS if w not in cor or w not in s63]
    if missing:
        sys.exit(f"outcome vocabulary out of sync between Corollary 1b and §6.3: {missing}")
    if "corollary 1b" not in s63:
        sys.exit("§6.3 no longer cites Corollary 1b")

    # Propositions cited in §3 must still exist in the analysis draft.
    for prop in re.findall(r"Proposition \d", parts["s3"]):
        if prop not in (ROOT / "draft_analysis.md").read_text():
            sys.exit(f"§3 cites {prop}, which is not in draft_analysis.md")

    body = [
        "# Reading copy — §3 (setup, test, analysis) and §6.3 (the adaptive distiller)",
        "",
        "_Generated by `paper/make_read_s3_s63.py`; do not edit. Sources: `draft_s3_s5.md` (§3),_",
        "_`draft_analysis.md` (Corollaries 1 and 1b), `draft_s5_s6.md` (§6.3). The script fails if the_",
        "_four outcome labels stop matching across the two, which is the point of reading them together._",
        "",
        "---",
        "",
        parts["s3"],
        "",
        "### 3.7 Analysis (Propositions 1–3 sit here; reproduced below is the part §6.3 depends on)",
        "",
        parts["cor"],
        "",
        "---",
        "",
        parts["s63"],
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(body))
    print(f"wrote {OUT.relative_to(ROOT.parent)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
